// <auto-generated />
using System;
using Company_module.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Company_module.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251219123518_AddCompanyAttachmentTable")]
    partial class AddCompanyAttachmentTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Company_module.Models.DTO.CompanyAttachment", b =>
                {
                    b.Property<Guid>("attachmentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("companyid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("filename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("filepath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("filetype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("bit");

                    b.HasKey("attachmentid");

                    b.ToTable("companyattachment", (string)null);
                });

            modelBuilder.Entity("Company_module.Models.DTO.CompanyDetailEntity", b =>
                {
                    b.Property<Guid>("companyid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("allowworkrequest")
                        .HasColumnType("bit");

                    b.Property<bool>("billable")
                        .HasColumnType("bit");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("countryid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("currencyid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isdeleted")
                        .HasColumnType("bit");

                    b.Property<string>("language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phonenumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("pobox")
                        .HasColumnType("int");

                    b.Property<string>("purchaserequestemail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("settings")
                        .HasColumnType("bit");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("taxregistrationnumber")
                        .HasColumnType("int");

                    b.Property<int>("thresholdvalue")
                        .HasColumnType("int");

                    b.Property<string>("timezone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("vat")
                        .HasColumnType("int");

                    b.Property<string>("workrequesturl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("companyid");

                    b.ToTable("companydetail", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
