// <auto-generated />
using System;
using Company_module.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Company_module.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251222112153_AddCountryCurrency")]
    partial class AddCountryCurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Company_module.Models.DTO.CompanyAttachment", b =>
                {
                    b.Property<Guid>("attachmentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("companyid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("filename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("filepath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("filetype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("attachmentid");

                    b.HasIndex("companyid");

                    b.ToTable("companyattachment", (string)null);
                });

            modelBuilder.Entity("Company_module.Models.DTO.CompanyDetailEntity", b =>
                {
                    b.Property<Guid>("companyid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("allowworkrequest")
                        .HasColumnType("bit");

                    b.Property<bool>("billable")
                        .HasColumnType("bit");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("countryid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("currencyid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phonenumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("pobox")
                        .HasColumnType("int");

                    b.Property<string>("purchaserequestemail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("settings")
                        .HasColumnType("bit");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("taxregistrationnumber")
                        .HasColumnType("int");

                    b.Property<int>("thresholdvalue")
                        .HasColumnType("int");

                    b.Property<string>("timezone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("vat")
                        .HasColumnType("int");

                    b.Property<string>("workrequesturl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("companyid");

                    b.HasIndex("countryid");

                    b.HasIndex("currencyid");

                    b.ToTable("companydetail", (string)null);
                });

            modelBuilder.Entity("Company_module.Models.DTO.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Company_module.Models.DTO.Currency", b =>
                {
                    b.Property<Guid>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("CurrencyId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Company_module.Models.DTO.CompanyAttachment", b =>
                {
                    b.HasOne("Company_module.Models.DTO.CompanyDetailEntity", "CompanyDetail")
                        .WithMany("CompanyAttachments")
                        .HasForeignKey("companyid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyDetail");
                });

            modelBuilder.Entity("Company_module.Models.DTO.CompanyDetailEntity", b =>
                {
                    b.HasOne("Company_module.Models.DTO.Country", "Country")
                        .WithMany("CompanyDetails")
                        .HasForeignKey("countryid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Company_module.Models.DTO.Currency", "Currency")
                        .WithMany("CompanyDetails")
                        .HasForeignKey("currencyid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("Company_module.Models.DTO.CompanyDetailEntity", b =>
                {
                    b.Navigation("CompanyAttachments");
                });

            modelBuilder.Entity("Company_module.Models.DTO.Country", b =>
                {
                    b.Navigation("CompanyDetails");
                });

            modelBuilder.Entity("Company_module.Models.DTO.Currency", b =>
                {
                    b.Navigation("CompanyDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
