// <auto-generated />
using System;
using Company_module.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Company_module.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251218131843_AddCompanyDetailTable")]
    partial class AddCompanyDetailTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Company_module.Models.DTO.CompanyDetailEntity", b =>
                {
                    b.Property<Guid>("companyid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("companyname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("companyid");

                    b.ToTable("companydetail", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
